"""Per-step check scripts: generated here, filled in by the agent, run in the
sandbox. Stdlib only.

**The parser never translates LaTeX to SymPy.** `sympy.parsing.latex.parse_latex`
needs `antlr4` and is unavailable in a stdlib-only skill; even where it works its
grammar is a calculus-textbook fragment with no `\\mathbb{E}`, no
`\\operatorname{}`, no norms and no user macros. A hand-rolled translator would
mis-handle `dx`, implicit multiplication and subscript-versus-index at least
sometimes, and its bugs would surface as *false counterexamples* -- the one
failure mode this project treats as unrecoverable.

So the tool writes a stub carrying everything needed to translate the step -- the
source LaTeX, the macro-expanded LaTeX, each symbol's domain **and where that
domain came from**, and the side conditions -- and the agent fills in `build()`.
The result is auditable in a way a parser's internal AST is not: a `.py` file the
reader can open.

**An unfilled stub reports `untranslatable`**, which composes to `UNVERIFIED`. It
must never read as a step that passed, or a run that translated nothing would
report a clean paper.
"""
import os
import re

from . import sandbox
from . import engines as _engines

#: The exact text the agent replaces. Kept as a constant so the tests can assert
#: it still exists rather than silently filling nothing.
UNFILLED_BODY = (
    '    raise Untranslatable(\n'
    '        "not yet translated -- replace this body with the model of the step")\n')

_HEADER = '''\
r"""Check script for {step_id}

Generated by verifying-proofs. **Fill in `build()`** and rerun.

Step {ordinal} of {proof_id} ({kind}), from {file} at offset {offset}.
Ledger content hash: {content_hash}

Justifying prose:
    {prose}

Source LaTeX (macros already expanded):
    {math}

The claim to model:
{claims}
Symbol domains, and where each came from. **A symbol whose provenance is
`unknown` can never refute this step**: the harness reports no counterexample
against it, because sampling outside a domain the paper meant but never wrote
down is how a checker manufactures an error against correct mathematics.
{domains}
Side conditions this step needs:
{sideconds}
Contract: set TRANSLATION_CONFIDENCE honestly.
  faithful    -- the model is the step, symbol for symbol
  approximate -- something was idealised (an opaque atom, a dropped constant)
  partial     -- only part of the step is modelled
Anything other than `faithful` caps the severity at WEAK, whatever the outcome.
List in IGNORED_SYMBOLS any symbol you deliberately did not model; every symbol
in SYMBOLS must otherwise appear in the expression, or the run is downgraded to
UNVERIFIED (translation incomplete).
"""
'''


def _slug(step_id):
    return re.sub(r"[^A-Za-z0-9]+", "-", step_id).strip("-")


def _fmt_block(lines, indent="    "):
    return "\n".join(indent + l for l in lines) if lines else indent + "(none)"


def _domain_lines(step, symbols):
    out = []
    for name in step.get("symbols_used") or []:
        s = symbols.get(name)
        if not s:
            continue
        quote = ""
        if s.get("domain_evidence"):
            quote = " -- %s" % s["domain_evidence"][0].get("quote", "")
        out.append("%-14s %-26s (%s)%s"
                   % (s["normalized"], s.get("domain_hint") or "not stated",
                      s.get("domain_provenance"), quote))
    return out


def _claim_lines(step):
    out = []
    for f in step.get("claim_forms") or []:
        out.append("%-9s %s   %s   %s"
                   % (f.get("form", ""), f.get("lhs_tex", ""),
                      f.get("relation", ""), f.get("rhs_tex", "")))
    return out or [step.get("math_tex", "")]


def _sidecond_lines(step):
    return ["%-28s %-14s %s" % (c["kind"], c.get("status", ""),
                                c.get("expr_tex", ""))
            for c in step.get("side_conditions") or []]


def _domains_dict(step, symbols):
    out = {}
    for name in step.get("symbols_used") or []:
        s = symbols.get(name)
        if s:
            out[s["normalized"]] = s.get("domain_hint")
    return out


def stub_source(step, symbols, engine="rational", trials=24):
    """The full text of one check script, with `build()` left to be written."""
    doms = _domains_dict(step, symbols)
    header = _HEADER.format(
        step_id=step["id"], ordinal=step.get("ordinal"),
        proof_id=step.get("proof_id"), kind=step.get("kind"),
        file=(step.get("source") or {}).get("file"),
        offset=(step.get("source") or {}).get("offset"),
        content_hash=step.get("content_hash"),
        prose=(step.get("prose_tex") or "(none)").replace("\n", " "),
        math=(step.get("math_tex") or "").replace("\n", " "),
        claims=_fmt_block(_claim_lines(step)),
        domains=_fmt_block(_domain_lines(step, symbols)),
        sideconds=_fmt_block(_sidecond_lines(step)))

    relation = "="
    for f in step.get("claim_forms") or []:
        relation = f.get("relation") or "="
        break

    consts = (
        'STEP_ID = %r\n'
        'ENGINE = %r\n'
        'CONTENT_HASH = %r\n'
        'TRANSLATION_CONFIDENCE = "faithful"\n'
        'TRANSLATION_NOTES = ""\n'
        'IGNORED_SYMBOLS = []\n'
        'SYMBOLS = %r\n'
        'DOMAINS = %r\n'
        'RELATION = %r\n'
        'TRIALS = %d\n'
        % (step["id"], engine, step.get("content_hash"),
           sorted(doms), doms, relation, trials))

    build = (
        '\n\ndef build():\n'
        '    """Model this step.\n\n'
        '    Return `(lhs, rhs, relation)`. For the rational engine `lhs` and\n'
        '    `rhs` are callables taking a dict of Fraction-valued symbols; for\n'
        '    the symbolic engine they are SymPy expressions.\n\n'
        '    Raise `Untranslatable("why")` if the step cannot be modelled\n'
        '    faithfully. That is a result, not a failure.\n'
        '    """\n'
        + UNFILLED_BODY)

    harness = _engines.harness_for(engine)
    if harness is None:
        raise ValueError("engine %r emits no check script" % engine)
    main = _MAIN.get(engine)
    if main is None:
        raise ValueError("engine %r has no entry point" % engine)
    return header + "\n" + harness + "\n" + consts + build + "\n" + main


_MAIN_RATIONAL = '''
if __name__ == "__main__":
    import json as _json
    import sys as _sys
    try:
        _lhs, _rhs, _rel = build()
        _out = check(_lhs, _rhs, _rel, SYMBOLS, DOMAINS, STEP_ID, TRIALS)
    except Untranslatable as _exc:
        _out = {"step_id": STEP_ID, "engine": ENGINE,
                "outcome": "untranslatable", "detail": str(_exc),
                "trials": 0, "rejected_samples": 0, "counterexample": None}
    _out["translation_confidence"] = TRANSLATION_CONFIDENCE
    _out["translation_notes"] = TRANSLATION_NOTES
    _out["content_hash"] = CONTENT_HASH
    _sys.stdout.write(_json.dumps(_out))
'''

_MAIN_SYMBOLIC = '''
if __name__ == "__main__":
    import json as _json
    import sys as _sys
    try:
        _lhs, _rhs, _rel = build()
        _out = check(_lhs, _rhs, _rel, SYMBOLS, IGNORED_SYMBOLS, STEP_ID)
    except Untranslatable as _exc:
        _out = {"step_id": STEP_ID, "engine": ENGINE,
                "outcome": "untranslatable", "detail": str(_exc),
                "counterexample": None}
    _out["translation_confidence"] = TRANSLATION_CONFIDENCE
    _out["translation_notes"] = TRANSLATION_NOTES
    _out["content_hash"] = CONTENT_HASH
    _sys.stdout.write(_json.dumps(_out))
'''

_MAIN_GRADIENT = '''
if __name__ == "__main__":
    import json as _json
    import sys as _sys
    try:
        _f, _claimed, _point, _var = build()
        _out = check(_f, _claimed, _point, _var, STEP_ID)
    except Untranslatable as _exc:
        _out = {"step_id": STEP_ID, "engine": ENGINE,
                "outcome": "untranslatable", "detail": str(_exc),
                "counterexample": None}
    _out["translation_confidence"] = TRANSLATION_CONFIDENCE
    _out["translation_notes"] = TRANSLATION_NOTES
    _out["content_hash"] = CONTENT_HASH
    _sys.stdout.write(_json.dumps(_out))
'''

_MAIN_SMT = '''
if __name__ == "__main__":
    import json as _json
    import sys as _sys
    try:
        _claim, _vars = build()
        _out = check(_claim, _vars, DOMAINS, STEP_ID)
    except Untranslatable as _exc:
        _out = {"step_id": STEP_ID, "engine": ENGINE,
                "outcome": "untranslatable", "detail": str(_exc),
                "counterexample": None}
    _out["translation_confidence"] = TRANSLATION_CONFIDENCE
    _out["translation_notes"] = TRANSLATION_NOTES
    _out["content_hash"] = CONTENT_HASH
    _sys.stdout.write(_json.dumps(_out))
'''

#: Entry point per engine. Each build() has a different signature because each
#: engine models a different kind of claim.
_MAIN = {"rational": _MAIN_RATIONAL, "symbolic": _MAIN_SYMBOLIC,
         "gradient": _MAIN_GRADIENT, "smt": _MAIN_SMT}

_CONTRACT = """\
# Check-script contract

One script per mechanically checkable step. Fill in `build()`; leave everything
else alone.

## What to return

`build()` returns `(lhs, rhs, relation)`.

- **rational engine** -- `lhs` and `rhs` are callables taking one dict mapping a
  symbol's normalised name to a `Fraction`, and returning a `Fraction`.
- **symbolic engine** -- `lhs` and `rhs` are SymPy expressions.

Raise `Untranslatable("why")` when the step cannot be modelled faithfully. That
is a legitimate result and it is reported as `UNVERIFIED`, not hidden.

## Honesty fields

| Field | Meaning |
|---|---|
| `TRANSLATION_CONFIDENCE` | `faithful`, `approximate`, or `partial`. Anything but `faithful` caps the severity at `WEAK` no matter what the check found. |
| `TRANSLATION_NOTES` | What was idealised, in one line. |
| `IGNORED_SYMBOLS` | Symbols deliberately not modelled. Every symbol in `SYMBOLS` must otherwise appear in the expression, or the result is downgraded to `UNVERIFIED (translation incomplete)`. |

## Rules the harness enforces for you

- A symbol whose domain provenance is `unknown` can never yield a counterexample.
- Sample points respect each symbol's declared domain, and exclude 0 and +-1.
- More than half the points degenerate means `UNVERIFIED`, never a pass.
- The rational engine can only refute. It never prints "verified".

## What an unfilled script does

It reports `untranslatable`, which composes to `UNVERIFIED`. A run in which
nothing was translated reports nothing checked -- never a clean paper.
"""


def write_stubs(ledger, outdir, engines=("rational",), trials=24):
    """One script per checkable step **per requested engine**. Returns the paths.

    This used to take the first name in `_engines.SCRIPTED` that appeared in the
    request and fall back to `rational` when none did. Both halves were silent
    and both were wrong:

    - `--engines sideconds,rational,symbolic` -- the example in `SKILL.md` --
      wrote `rational` scripts and discarded `symbolic`. The Adam refutation that
      demonstrates the entire CAS path worked only because it was run *without*
      `rational` on the command line; adding it would have quietly disabled the
      engine the result depends on.
    - `--engines named` wrote `rational` scripts, because `named` has no harness.
      Asking for one engine and silently receiving another is worse than being
      refused.

    Two engines on one step is the case the severity ladder was built for --
    `compose_step` already takes a list of results per step and has a rule for
    engines that disagree -- so the filename now carries the engine and both run.
    """
    wanted = [e for e in (engines or ()) if e != "sideconds"] or ["rational"]
    unscripted = [e for e in wanted if _engines.harness_for(e) is None]
    if unscripted:
        raise ValueError(
            "%s emits no check script. Scripted engines are: %s"
            % (", ".join(repr(e) for e in unscripted),
               ", ".join(_engines.SCRIPTED)))

    checks = os.path.join(outdir, "checks") if os.path.basename(outdir) != "checks" \
        else outdir
    os.makedirs(checks, exist_ok=True)
    symbols = {s["symbol"]: s for s in ledger.get("symbols", [])}

    with open(os.path.join(checks, "_contract.md"), "w", encoding="utf-8") as fh:
        fh.write(_CONTRACT)

    paths = []
    for step in ledger.get("steps", []):
        if step.get("checkable") != "candidate":
            continue
        for engine in wanted:
            # The engine is in the *filename*, not only in the file. Two engines
            # on one step wrote to the same path before, so the second silently
            # overwrote the first.
            path = os.path.join(checks, "%s.%s.py" % (_slug(step["id"]), engine))
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(stub_source(step, symbols, engine, trials))
            paths.append(path)
    return paths


def collect(outdir, timeout=sandbox.DEFAULT_TIMEOUT, budget=300):
    """Run every check script, newest budget first. Never raises."""
    checks = os.path.join(outdir, "checks") if os.path.basename(outdir) != "checks" \
        else outdir
    if not os.path.isdir(checks):
        return []
    out, spent = [], 0.0
    import time
    for name in sorted(os.listdir(checks)):
        if not name.endswith(".py"):
            continue
        if spent > budget:
            out.append({"outcome": "unverified", "engine": None,
                        "detail": "run budget of %ss exhausted before this step"
                                  % budget,
                        "script": os.path.join("checks", name)})
            continue
        t0 = time.time()
        r = sandbox.run_script(os.path.join(checks, name), timeout=timeout)
        spent += time.time() - t0
        r["script"] = os.path.join("checks", name)
        out.append(r)
    return out
